### ISSUE TITLE
Refactoring repetitive codes with DRY principle.

### ISSUE THREAD

**Issue by enverarslan** [tarikguney/manager-automation-v2#3]
When I watch youtube video, I realized your message handler part of some actors are same.

Examples: 
- https://github.com/tarikguney/manager-automation-v2/blob/master/src/TarikGuney.ManagerAutomation.FunctionApp/Actors/MissingDescriptionFinderActor.cs#L58-L77
- https://github.com/tarikguney/manager-automation-v2/blob/master/src/TarikGuney.ManagerAutomation.FunctionApp/Actors/NonDescriptiveTitlesFinderActor.cs#L50-L70
- https://github.com/tarikguney/manager-automation-v2/blob/master/src/TarikGuney.ManagerAutomation.FunctionApp/Actors/WorkItemsWithoutEstimationFinderActor.cs#L55-L74

Do you consider to refactoring this parts with external method or class or type?

**Comment by tarikguney** [comment]
Good catch. When I first began the project, it was not big of a deal as sometimes the abstraction that comes with DRY convolutes the code base more than repeating the code a couple of times here and there. So, I am not 100% sure if that is worth the effort there. I will check one more, and perhaps abstract that common logic away under a generic class or by using composition instead of inheritance.

**Comment by enverarslan** [comment]
I don't have deep knowledge about .net data structures but somehow this code can be converted as generic.

Actually, in above files, Actors are only filtering `workItems` with different specific fields and pass data to bus. And this different fields are affecting content of messages. This makes us think of the whole Actor. 

In fact, we must ask ourself these questions:

- Where is the end of DRY improvements?
- Is Actor responsible for querying, filtering data?
- Is Actor responsible for building message?
- If Actor is [smallest unit of application](https://getakka.net/articles/concepts/actors.html#actors:~:text=The%20previous%20section%20about%20Actor%20Systems,smallest%20unit%20when%20building%20an%20application.), how we consider SoC?

I opened this issue for thinking refactoring when rewriting to application. Also I am curious about how Actor model separates works and Azure Functions simplifies.

Can you talk about next live stream?

**Comment by tarikguney** [comment]
Sure! Thanks for the input @enverarslan.
